### ISSUE TITLE
Crear las URI de acceso para MongoDB 

### ISSUE THREAD

**Issue by Andres2310** [Open-Bootcamp/ghibli-app-back#1]
Para tener un entorno de desarrollo seguro necesitamos URI individuales y 1 certificado para llevarlo a producción.

La persona encargada de hacer esto se volverá inmediatamente en el administrador del cluster de MongoDB

**Comment by AleVedoya** [comment]
Me asigné esta issue.
Ya se creó la URI de acceso para MongoDB
Se crearon 3 usuarios

**Comment by AleVedoya** [comment]
Ya se terminó la issue :)

**Comment by Andres2310** [comment]
Probe el acceso con mis datos y todo funciona bien gracias Ale
