### ISSUE TITLE
Añadir a la ruta films, una ruta por id para retornar 1 solo film de studio ghibli

### ISSUE THREAD

**Issue by Andres2310** [Open-Bootcamp/ghibli-app-back#10]
Ahora que ya tenemos la base de datos y sabemos que nos retorna los valores podemos dar una nueva feature y tener una ruta por id de mongoDB

`/films/2sqw31qs3w217ad783asd2`

Por ejemplo

**Comment by AleVedoya** [comment]
Me asigné esta issue

**Comment by AleVedoya** [comment]
Se añadio el GET de la ruta por id
