### ISSUE TITLE
Desarrollo de la ruta films con sus métodos GET y POST

### ISSUE THREAD

**Issue by Andres2310** [Open-Bootcamp/ghibli-app-back#3]
Programar la ruta /films en la carpeta routes con el nombre filmsRoute.js

```
routes
 └filmsRoute.js
```

Programar un método GET y POST que respete el esquema que se creo para guardar los films de Studio Ghibli

**Comment by AleVedoya** [comment]
Ya se terminó la issue. Se hicieron los métodos GET y POST
