### ISSUE TITLE
Añadir un status 404 para cuando se busca un id inexistente o que se a borrado

### ISSUE THREAD

**Issue by Andres2310** [Open-Bootcamp/ghibli-app-back#30]
Cuando se usa de ruta films/:id cuando se pone un id no disponible en la base de datos se obtiene un error no legible para un usuario, para evitar problemas debemos mandar un status acorde a lo que sucede en el lado del back-end junto con un mensaje legible

**Comment by AleVedoya** [comment]
Me asigné la issue

**Comment by AleVedoya** [comment]
Se agregó el status 404 en los archivos controllerFilms.js y controllerCharacters.js
