### ISSUE TITLE
Crear esquema para guardar los personajes en la base de datos de MongoDB

### ISSUE THREAD

**Issue by Andres2310** [Open-Bootcamp/ghibli-app-back#4]
Ya definimos cual seria la forma final del JSON para mostrar los personajes del Studio Ghibli con el equipo de FrontEnd asi que la persona encargada de esta tarea debe respetar el output que se muestra abajo para crear el esquema con mongoose en la carpeta models

```
models
  └characters.js
```

```
{
  "id": "ca568e87-4ce2-4afa-a6c5-51f4ae80a60b",
  "name": "Shishigami",
  "age": "400",
  "gender": "Male",
  "films": [
    "https://ghibliapi.herokuapp.com/films/0440483e-ca0e-4120-8c50-4c8cd9b965d6"
  ],
  "url": "cloudinary/image"
}
```

**Comment by JonatanHN** [comment]
**Hi bro**
