### ISSUE TITLE
Crear el controlador films con los métodos GET y POST hechos previamente

### ISSUE THREAD

**Issue by Andres2310** [Open-Bootcamp/ghibli-app-back#9]
crear el controlador en la carpeta controller con el nombre controllerFilms.js con la lógica programada previamente
```
controllers
  └controllerFilms.js
```

**Comment by AleVedoya** [comment]
Me autoasigné esta issue

**Comment by AleVedoya** [comment]
Ya hice el controlador films e hice el GET

**Comment by AleVedoya** [comment]
Hice el Post en controllerFilms.js

**Comment by AleVedoya** [comment]
Terminé la issue
